

target_dataset: "DIRECTORY_OF_TARGET_IMAGES"
batch_size: 64
face_recognition_config: "./face_recognition_model/adaface_config.yaml"
observer_data: "./observer/observer_data.pkl"
outpath: "./observer/qualities.pkl"
    