
dataset:
  path: "./calibration_dataset"
  batch_size: 8
  mpx: 14
  image_size: 112
  alphas: [1.e-3]

face_recognition_config: "./face_recognition_model/adaface_config.yaml"
outpath: "./baselineFIQA/pseudo_quality_labels.pkl"
    